#!/usr/bin/env python3

import os
from vx_library import init_setup

if not os.geteuid() == 0:
    print("This command must be used with 'sudo'.vx")
else:
    setup = init_setup()
    setup(os.path.dirname(os.path.abspath(__file__)))
