#!/usr/bin/env python3

import os
from vx_library import Manager

setup = Manager.setup()

if not os.geteuid() == 0:
    setup.warn("This command must be used with 'sudo'")
else:
    setup.run(os.path.dirname(os.path.abspath(__file__)))
