#!./.venv/bin/python

"""
Author            : Nohavye
Author's Email    : noha.poncelet@gmail.com
Repository        : https://github.com/vixen-shell/vixen-shell.git
Description       : Vixen manager executable.
License           : GPL3
"""

import os, argparse, sys

os.environ["GDK_BACKEND"] = "wayland"
from vx_library import Manager


def handle_path(args):
    return args.path or os.getcwd()


def handle_args(args):
    path = handle_path(args)

    if args.env:
        if args.env == "install":
            if not args.package:
                print(
                    "You must specify a package name with the [--package PACKAGE] option"
                )
                return

            Manager.Setup.install_package(args.package)

        if args.env == "uninstall":
            if not args.package:
                print(
                    "You must specify a package name with the [--package PACKAGE] option"
                )
                return

            Manager.Setup.uninstall_package(args.package)

    if args.setup:
        if args.setup == "update":
            Manager.Setup.update()

        if args.setup == "remove":
            Manager.Setup.remove()

    elif args.shell:
        if args.shell == "open":
            sys.path.append("/usr/share/vixen/features")
            Manager.Shell.open()

        if args.shell == "close":
            Manager.Shell.close()

    elif args.dev:
        if args.dev == "run":
            Manager.Shell.dev(path)

        if args.dev == "new":
            Manager.Setup.create_feature(path)

    elif args.feature:
        if args.feature == "names":
            Manager.Shell.feature_names()

        if args.feature == "add":
            Manager.Setup.add_feature(path)

        if args.feature == "remove":
            Manager.Setup.remove_feature()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=f"""
        Vixen Manager.
    """
    )

    root_args = parser.add_mutually_exclusive_group(required=True)

    root_args.add_argument(
        "--env",
        type=str,
        choices=["install", "uninstall"],
        help="Vixen environment controls.",
    )
    root_args.add_argument(
        "--setup",
        type=str,
        choices=["update", "remove"],
        help="Vixen Shell setup.",
    )
    root_args.add_argument(
        "--shell",
        type=str,
        choices=["open", "close"],
        help="Vixen Shell controls.",
    )
    root_args.add_argument(
        "--dev", type=str, choices=["run", "new"], help="Vixen Shell devs controls."
    )
    root_args.add_argument(
        "--feature",
        type=str,
        choices=["names", "add", "remove"],
        help="Vixen Shell features controls.",
    )

    parser.add_argument("--path", type=str, default="", help="Optional path")
    parser.add_argument("--package", type=str, default="", help="Environment package")

    handle_args(parser.parse_args())
