#!./.venv/bin/python

"""
Author            : Nohavye
Author's Email    : noha.poncelet@gmail.com
Repository        : https://github.com/vixen-shell/vixen-shell.git
Description       : Vixen manager executable.
License           : GPL3
"""

from vx_manager import Manager

Manager.handle_args()
